name: Build And Deploy
on:
  push:
    branches: [ master ]
  pull_request:
jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Deeps
        run: yarn install

      - name: Run Test
        run: yarn test:cov ## could do something with cov in future

      - name: Run Lint
        run: yarn lint

      - name: Run Build
        run: yarn build
  test-worker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Deeps
        run: yarn install

      - name: Run Test
        run: yarn test:cov ## could do something with cov in future

      - name: Run Lint
        run: yarn lint

      - name: Run Build
        run: yarn build